/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smart.manager;

import java.awt.Cursor;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Hacker
 */
public class Income extends javax.swing.JFrame {

    /**
     * Creates new form Income
     */
    public String UserType="User";
    public String Id;
    public String Name;
    Calendar cal= Calendar.getInstance();
    int salary=0;
    int buss=0;
    int otherincome=0;
    int bank=0;
    public int total=0;
    String Source="";
    public Income() {
        initComponents();
        sal.setEnabled(false);
        business.setEnabled(false);
        other.setEnabled(false);
        interest.setEnabled(false);
        date.setText(cal.getTime().toString());
        idlabel.setText(Id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        out = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        idlabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        salarycheckbox = new javax.swing.JCheckBox();
        businesscheckbox = new javax.swing.JCheckBox();
        othercheckbox = new javax.swing.JCheckBox();
        interestcheckbox = new javax.swing.JCheckBox();
        sal = new javax.swing.JTextField();
        business = new javax.swing.JTextField();
        other = new javax.swing.JTextField();
        interest = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        date = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SMART MANAGER");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INCOME SOURCES");

        out.setBackground(new java.awt.Color(0, 0, 204));
        out.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart/manager/image/icons8_Shutdown_40px_1.png"))); // NOI18N
        out.setFocusable(false);
        out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                outMouseEntered(evt);
            }
        });
        out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(0, 0, 204));
        back.setForeground(new java.awt.Color(0, 0, 204));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart/manager/image/icons8_Back_Arrow_64px.png"))); // NOI18N
        back.setFocusable(false);
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart/manager/image/icons8_Rupee_48px.png"))); // NOI18N

        name.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        name.setForeground(new java.awt.Color(255, 0, 0));
        name.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(out))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel13)
                    .addComponent(out))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));

        idlabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idlabel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Developed by Avinash Kumar Singh (CSE 3rd Year)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(idlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        salarycheckbox.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        salarycheckbox.setForeground(new java.awt.Color(0, 0, 153));
        salarycheckbox.setText("SALARY :-");
        salarycheckbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salarycheckboxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salarycheckboxMouseEntered(evt);
            }
        });
        salarycheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salarycheckboxActionPerformed(evt);
            }
        });

        businesscheckbox.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        businesscheckbox.setForeground(new java.awt.Color(0, 0, 153));
        businesscheckbox.setText("BUSINESS :-");
        businesscheckbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                businesscheckboxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                businesscheckboxMouseEntered(evt);
            }
        });

        othercheckbox.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        othercheckbox.setForeground(new java.awt.Color(0, 0, 153));
        othercheckbox.setText("OTHER SOURCE :-");
        othercheckbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                othercheckboxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                othercheckboxMouseEntered(evt);
            }
        });

        interestcheckbox.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        interestcheckbox.setForeground(new java.awt.Color(0, 0, 153));
        interestcheckbox.setText("INTEREST BY BANKS :-");
        interestcheckbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                interestcheckboxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                interestcheckboxMouseEntered(evt);
            }
        });
        interestcheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interestcheckboxActionPerformed(evt);
            }
        });

        sal.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        sal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                salKeyTyped(evt);
            }
        });

        business.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        business.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                businessActionPerformed(evt);
            }
        });
        business.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                businessKeyTyped(evt);
            }
        });

        other.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        other.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                otherKeyTyped(evt);
            }
        });

        interest.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        interest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interestActionPerformed(evt);
            }
        });
        interest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                interestKeyTyped(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart/manager/image/icons8_Rupee_50px.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart/manager/image/icons8_Rupee_50px.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart/manager/image/icons8_Rupee_50px.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart/manager/image/icons8_Rupee_50px.png"))); // NOI18N

        submit.setBackground(new java.awt.Color(51, 153, 0));
        submit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart/manager/image/icons8_Enter_52px.png"))); // NOI18N
        submit.setText("SUBMIT");
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submitMouseEntered(evt);
            }
        });
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        cancel.setBackground(new java.awt.Color(255, 0, 0));
        cancel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart/manager/image/icons8_Cancel_52px.png"))); // NOI18N
        cancel.setText("CANCEL");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelMouseEntered(evt);
            }
        });
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        date.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        date.setForeground(new java.awt.Color(255, 0, 0));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Date & Time :-");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Select Your Income Source");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart/manager/image/icons8_Hand_Right_35px.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart/manager/image/icons8_Hand_Right_35px.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart/manager/image/icons8_Hand_Right_35px.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart/manager/image/icons8_Hand_Right_35px.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(businesscheckbox)
                            .addComponent(othercheckbox)
                            .addComponent(interestcheckbox)
                            .addComponent(salarycheckbox))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(business, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                                    .addComponent(other)
                                    .addComponent(interest)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(submit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sal, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 122, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(sal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8)
                        .addComponent(salarycheckbox)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(business, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel9)
                        .addComponent(businesscheckbox)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(othercheckbox)
                            .addComponent(other, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(interestcheckbox)
                            .addComponent(interest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit)
                    .addComponent(cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(1119, 701));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salarycheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salarycheckboxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_salarycheckboxActionPerformed

    private void interestcheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interestcheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interestcheckboxActionPerformed

    private void businessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_businessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_businessActionPerformed

    private void interestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interestActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        if(salarycheckbox.isSelected()&&sal.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "You Selected Salary but you do not mention any Salary");
        }
        else if(businesscheckbox.isSelected()&&business.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "You Selected Bussiness but you do not mention any Amount");
        }
        else if(othercheckbox.isSelected()&&other.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "You Selected Other Salary but you do not mention any Amount");
        }
        else if(interestcheckbox.isSelected()&&interest.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "You Selected Interest by Bank but you do not mention any Amount");
        }
        else
        {
        if(!(sal.getText().equals("")))
        {
            salary=Integer.parseInt(sal.getText());
            Source=Source+"Salary- Rs"+String.valueOf(salary)+",\n";
        }
        if(!(business.getText().equals("")))
        {
            buss=Integer.parseInt(business.getText());
            Source=Source+"Business- Rs"+String.valueOf(buss)+",\n";
        }
        if(!(other.getText().equals("")))
        {
            otherincome=Integer.parseInt(other.getText());
            Source=Source+"Other- Rs"+String.valueOf(otherincome)+",\n";
        }
        if(!(interest.getText().equals("")))
        {
            bank=Integer.parseInt(interest.getText());
            Source=Source+"Bank- Rs"+String.valueOf(bank)+",\n";
        }
        if((sal.getText().equals(""))&&(business.getText().equals(""))&&(other.getText().equals(""))&&(interest.getText().equals("")))
        {
           JOptionPane.showMessageDialog(null, "Plese Enter atleast One Income Source to Submit","Information",JOptionPane.INFORMATION_MESSAGE );
        }
        else
        {
        total=salary+buss+otherincome+bank;
        java.util.Date currentDate=cal.getTime();
       try{
               Class.forName("oracle.jdbc.driver.OracleDriver");
               Connection conn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","avinash");
               PreparedStatement ps=conn.prepareStatement("insert into income values(?,?,?,?,?,?)");
               ps.setDate(1,new java.sql.Date(currentDate.getTime()));
               ps.setString(2,Id);
               ps.setString(3,Name);
               ps.setString(4,Source);
               ps.setString(5,"INCOME");
               ps.setString(6,String.valueOf(total));
               ps.executeUpdate();
               JOptionPane.showMessageDialog(null, "Income Data Submitted Successfully");
               Choice choice=new Choice();
               choice.Id=Id;
               choice.idlabel.setText(Id);
               choice.Name=Name;
               choice.welcometext.setText(Name);
               switch (UserType) {
                case "Admin":
                    choice.UserType="Admin";
                    break;
                case "Manager":
                    choice.UserType="Manager";
                    break;
                default:
                    choice.UserType="User";
                    break;
            }
             conn.close();
             ps.close();
           
               choice.setVisible(true);
               this.setVisible(false);
            }
            catch(HeadlessException | ClassNotFoundException | SQLException e){
                JOptionPane.showMessageDialog(null, e);
            } 
        }
        }
    }//GEN-LAST:event_submitActionPerformed
    private JFrame frame;
    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        frame=new JFrame("Exit");
        if(JOptionPane.showConfirmDialog( frame,"Are You Sure Want to close the Application"," SMART MANAGER",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_cancelActionPerformed

    private void outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outActionPerformed
        // TODO add your handling code here:
        frame=new JFrame("Exit");
        if(JOptionPane.showConfirmDialog( frame,"Are You Sure Want to Log-out"," SMART MANAGER",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        {
        Welcome welcome=new Welcome();
        welcome.setVisible(true);
        this.setVisible(false);
        }
    }//GEN-LAST:event_outActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        Choice choice=new Choice();
        choice.Id=Id;
        choice.UserType=UserType;
        choice.idlabel.setText(Id);
        choice.Name=Name;
        choice.welcometext.setText(Name);
        switch (UserType) {
            case "Admin":
                choice.UserType="Admin";
                break;
            case "Manager":
                choice.UserType="Manager";
                break;
            default:
                choice.UserType="User";
                break;
        }
        choice.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void salarycheckboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salarycheckboxMouseClicked
        // TODO add your handling code here:
        if(salarycheckbox.isSelected())
        {
        sal.setEnabled(true);
        }
        else
        {
            sal.setEnabled(false);
        }
    }//GEN-LAST:event_salarycheckboxMouseClicked

    private void businesscheckboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_businesscheckboxMouseClicked
        // TODO add your handling code here:
        if(businesscheckbox.isSelected())
            {
        business.setEnabled(true);
        }
        else
        {
            business.setEnabled(false);
        }
    }//GEN-LAST:event_businesscheckboxMouseClicked

    private void othercheckboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_othercheckboxMouseClicked
        // TODO add your handling code here:
        if(othercheckbox.isSelected())
        {
            other.setEnabled(true);
        }
        else
        {
            other.setEnabled(false);
        }
    }//GEN-LAST:event_othercheckboxMouseClicked

    private void interestcheckboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_interestcheckboxMouseClicked
        // TODO add your handling code here:
        if(interestcheckbox.isSelected())
        {
            interest.setEnabled(true);
        }
        else
        {
            interest.setEnabled(false);
        }
    }//GEN-LAST:event_interestcheckboxMouseClicked

    private void salKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salKeyTyped
        // TODO add your handling code here:
        char ch=evt.getKeyChar();
        if(!(Character.isDigit(ch)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_salKeyTyped

    private void businessKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_businessKeyTyped
        // TODO add your handling code here:
         char ch=evt.getKeyChar();
        if(!(Character.isDigit(ch)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_businessKeyTyped

    private void otherKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_otherKeyTyped
        // TODO add your handling code here:
         char ch=evt.getKeyChar();
        if(!(Character.isDigit(ch)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_otherKeyTyped

    private void interestKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_interestKeyTyped
        // TODO add your handling code here:
         char ch=evt.getKeyChar();
        if(!(Character.isDigit(ch)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_interestKeyTyped

    private void salarycheckboxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salarycheckboxMouseEntered
        // TODO add your handling code here:
        salarycheckbox.setCursor(Cursor.getPredefinedCursor((Cursor.HAND_CURSOR)));
    }//GEN-LAST:event_salarycheckboxMouseEntered

    private void businesscheckboxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_businesscheckboxMouseEntered
        // TODO add your handling code here:
        businesscheckbox.setCursor(Cursor.getPredefinedCursor((Cursor.HAND_CURSOR)));
    }//GEN-LAST:event_businesscheckboxMouseEntered

    private void othercheckboxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_othercheckboxMouseEntered
        // TODO add your handling code here:
        othercheckbox.setCursor(Cursor.getPredefinedCursor((Cursor.HAND_CURSOR)));
    }//GEN-LAST:event_othercheckboxMouseEntered

    private void interestcheckboxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_interestcheckboxMouseEntered
        // TODO add your handling code here:
        interestcheckbox.setCursor(Cursor.getPredefinedCursor((Cursor.HAND_CURSOR)));
    }//GEN-LAST:event_interestcheckboxMouseEntered

    private void submitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseEntered
        // TODO add your handling code here:
        submit.setCursor(Cursor.getPredefinedCursor((Cursor.HAND_CURSOR)));
    }//GEN-LAST:event_submitMouseEntered

    private void cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseEntered
        // TODO add your handling code here:
        cancel.setCursor(Cursor.getPredefinedCursor((Cursor.HAND_CURSOR)));
    }//GEN-LAST:event_cancelMouseEntered

    private void outMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outMouseEntered
        // TODO add your handling code here:
        out.setCursor(Cursor.getPredefinedCursor((Cursor.HAND_CURSOR)));
    }//GEN-LAST:event_outMouseEntered

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        // TODO add your handling code here:
        back.setCursor(Cursor.getPredefinedCursor((Cursor.HAND_CURSOR)));
    }//GEN-LAST:event_backMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Income.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Income.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Income.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Income.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Income().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField business;
    private javax.swing.JCheckBox businesscheckbox;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel date;
    public javax.swing.JLabel idlabel;
    private javax.swing.JTextField interest;
    private javax.swing.JCheckBox interestcheckbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel name;
    private javax.swing.JTextField other;
    private javax.swing.JCheckBox othercheckbox;
    private javax.swing.JButton out;
    private javax.swing.JTextField sal;
    private javax.swing.JCheckBox salarycheckbox;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
